### ISSUE TITLE
unicode pt-br

### ISSUE THREAD

**Issue by victhor9696** [Alheimsins/b5-50-ipip-neo-pi-r#74]
I think the unicode of pt-br is in problem, has some <?>

the ideal would be to come like this

[
  {
    "id": "58d571e5-d725-4cf8-a438-32c16ee28eb6",
    "text": "Acredite na importáncia da arte",
    "keyed": "plus",
    "domain": "O"
  },
  {
    "id": "888dd864-7449-4e96-8d5c-7a439603ea91",
    "text": "Tenha uma imaginação vívida",
    "keyed": "plus",
    "domain": "O"
  },
  {
    "id": "79186f48-e7fa-4df4-b74b-b0627ee244e1",
    "text": "Procure votar em políticos liberais",
    "keyed": "plus",
    "domain": "O"
  },
  {
    "id": "f5987fe3-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Leve a conversa para um nível mais elevado",
    "keyed": "plus",
    "domain": "O"
  },
  {
    "id": "f5987fe4-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Escute novas ideias",
    "keyed": "plus",
    "domain": "O"
  },
  {
    "id": "b99a005c-090c-454d-a905-dd0082a33ee3",
    "text": "Não estou interessado em ideias abstratas",
    "keyed": "minus",
    "domain": "O"
  },
  {
    "id": "0f7c46a9-206f-4904-878c-cc04c80b2b73",
    "text": "Não gosta de arte",
    "keyed": "minus",
    "domain": "O"
  },
  {
    "id": "95a3f20c-f933-4d19-a2c1-a7dbdf63c562",
    "text": "Evite discussções filosóficas",
    "keyed": "minus",
    "domain": "O"
  },
  {
    "id": "87c5b27e-59a8-4c48-8ba8-f5413d735693",
    "text": "Não gosta de ir a museus de arte",
    "keyed": "minus",
    "domain": "O"
  },
  {
    "id": "96ba77b2-1a44-4dfd-95f9-ae4d1f714460",
    "text": "Tendem a votar em candidatos políticos conservadores",
    "keyed": "minus",
    "domain": "O"
  },
  {
    "id": "5e8550d7-b8ef-4905-950a-f81d735d39e2",
    "text": "Muitas vezes, me sinto triste",
    "keyed": "plus",
    "domain": "N"
  },
  {
    "id": "f0a14e16-d726-47e9-a2c1-647fd3d7d52e",
    "text": "Não gosto de mim mesmo",
    "keyed": "plus",
    "domain": "N"
  },
  {
    "id": "743d8973-1de1-4485-91b4-8a5cf63e7d44",
    "text": "Muitas vezes estou para baixo",
    "keyed": "plus",
    "domain": "N"
  },
  {
    "id": "815e5ed1-f142-4fde-8c66-c1c2908355a7",
    "text": "Seja sempre bem humorado",
    "keyed": "plus",
    "domain": "N"
  },
  {
    "id": "2f519935-92e8-48ad-9746-4a0f8b38466a",
    "text": "Facilmente em pânico",
    "keyed": "plus",
    "domain": "N"
  },
  {
    "id": "fc8c518e-30b7-4ccd-a7a3-bc7452b888d8",
    "text": "Raramente fico irritado",
    "keyed": "minus",
    "domain": "N"
  },
  {
    "id": "d588951f-9f6f-43ac-bb56-733e3ad31ea5",
    "text": "Raramente me sinto triste",
    "keyed": "minus",
    "domain": "N"
  },
  {
    "id": "f40e421f-6c24-4be2-bd9f-28d33358d8c6",
    "text": "Me sinto confortável comigo mesmo",
    "keyed": "minus",
    "domain": "N"
  },
  {
    "id": "c283c5bd-4708-432e-92c1-63213aa28f59",
    "text": "Não me incomodo facilmente",
    "keyed": "minus",
    "domain": "N"
  },
  {
    "id": "7e20a189-d1cd-4864-814e-e814e778e53d",
    "text": "Estou muito satisfeito comigo mesmo",
    "keyed": "minus",
    "domain": "N"
  },
  {
    "id": "af55f014-788c-4b6e-92c4-b2b59dc8a28d",
    "text": "Sinta-se confortável com as outras pessoas",
    "keyed": "plus",
    "domain": "E"
  },
  {
    "id": "d50a597f-632b-4f7b-89e6-6d85b50fd1c9",
    "text": "Faço amigos facilmente",
    "keyed": "plus",
    "domain": "E"
  },
  {
    "id": "f5987ff6-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Sou especializado em lidar com situações sociais",
    "keyed": "plus",
    "domain": "E"
  },
  {
    "id": "f5987ff7-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Sou o espirito da festa",
    "keyed": "plus",
    "domain": "E"
  },
  {
    "id": "f5987ff8-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Saiba como cativar as pessoas",
    "keyed": "plus",
    "domain": "E"
  },
  {
    "id": "9cafc31e-9798-48dd-86b8-3140092836e3",
    "text": "Tenho pouco a dizer",
    "keyed": "minus",
    "domain": "E"
  },
  {
    "id": "e98b7166-6e28-4b07-adb8-a37b107d8259",
    "text": "Mantenha em segundo plano",
    "keyed": "minus",
    "domain": "E"
  },
  {
    "id": "f5987ffb-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Descreveria minhas experiências como um pouco enfadonhas",
    "keyed": "minus",
    "domain": "E"
  },
  {
    "id": "7e3469cc-5b19-472d-9efe-1ae4544ff533",
    "text": "Não gosto de chamar atenção para mim mesmo",
    "keyed": "minus",
    "domain": "E"
  },
  {
    "id": "f5987ffd-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Não sou de falar muito",
    "keyed": "minus",
    "domain": "E"
  },
  {
    "id": "f6076eea-56ae-4b46-97f1-5f94a7676c96",
    "text": "Estou sempre preparado",
    "keyed": "plus",
    "domain": "C"
  },
  {
    "id": "f5987fff-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Presto atenção nos detalhes",
    "keyed": "plus",
    "domain": "C"
  },
  {
    "id": "ed516b6b-2686-453e-8a7a-05fc1d8f1f64",
    "text": "Obtenha tarefas prontas",
    "keyed": "plus",
    "domain": "C"
  },
  {
    "id": "9d3cb5c7-955c-43a4-b6c7-b07ed01dcbd9",
    "text": "Executo meus planos",
    "keyed": "plus",
    "domain": "C"
  },
  {
    "id": "f5988002-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Faça planos e os cumpra",
    "keyed": "plus",
    "domain": "C"
  },
  {
    "id": "c7db0ed8-df7d-49bf-942f-59e46ef743c4",
    "text": "Perder meu tempo",
    "keyed": "minus",
    "domain": "C"
  },
  {
    "id": "f39aced8-60d5-4371-962e-b0d390dec3d3",
    "text": "Acho difícil começar a trabalhar",
    "keyed": "minus",
    "domain": "C"
  },
  {
    "id": "a9c97d6b-6721-4150-8d84-64ef3082f164",
    "text": "Basta trabalhar o suficiente para sobreviver",
    "keyed": "minus",
    "domain": "C"
  },
  {
    "id": "f5988006-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Não olhe para trás",
    "keyed": "minus",
    "domain": "C"
  },
  {
    "id": "f5988007-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Fugir dos meus deveres",
    "keyed": "minus",
    "domain": "C"
  },
  {
    "id": "4b4e9c5d-78d4-4b0a-b1ea-820077bb700a",
    "text": "Seja educado com todo mundo",
    "keyed": "plus",
    "domain": "A"
  },
  {
    "id": "6f66cdc0-9044-457b-b40d-501ecae15ee7",
    "text": "Acredite que os outros tenham boas intenções",
    "keyed": "plus",
    "domain": "A"
  },
  {
    "id": "f598a6f0-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Respeite os outros",
    "keyed": "plus",
    "domain": "A"
  },
  {
    "id": "f598a6f1-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Aceite as pessoas como elas são",
    "keyed": "plus",
    "domain": "A"
  },
  {
    "id": "f598a6f2-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Faça as pessoas se sentirem á vontade",
    "keyed": "plus",
    "domain": "A"
  },
  {
    "id": "027a663a-217d-4b3b-b9c7-c26498a9ab47",
    "text": "Tenha uma língua afiada",
    "keyed": "minus",
    "domain": "A"
  },
  {
    "id": "f598a6f4-ca1b-11e8-99c5-7b2468b8a6ec",
    "text": "Cortar os outros em pedaços",
    "keyed": "minus",
    "domain": "A"
  },
  {
    "id": "9ab95f24-5f94-429e-be1e-2275a806b5db",
    "text": "Suspeite de motivos ocultos em outros",
    "keyed": "minus",
    "domain": "A"
  },
  {
    "id": "17910a55-a64a-4ed0-8b46-293e2fa2fe03",
    "text": "Volte aos outros",
    "keyed": "minus",
    "domain": "A"
  },
  {
    "id": "0de0f900-cede-4538-9c00-5da4f830b028",
    "text": "Insultar pessoas",
    "keyed": "minus",
    "domain": "A"
  }
]

**Comment by zrrrzzt** [comment]
Thank you @victhor9696 👍 
Updated and published 4.0.1
